export const cartTypes = Object.freeze({
    SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
    SET_ITEMS:'SET_ITEMS',
    ADD_TO_CART:'ADD_TO_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    INCREASE_COUNT:'INCREASE_COUNT',
    DECREASE_COUNT:'DECREASE_COUNT'
})