export const productListTypes = Object.freeze({
    FETCH_ITEMS: 'FETCH_ITEMS',
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',
    SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',
})